### ISSUE TITLE
[Bugs] n3iwf connection error - Panic recovered

### ISSUE THREAD

**Issue by dayal007** [my5G/my5G-core#26]
I tried connecting the n3iwf UE to the my5g-core but got the following error:

my5g-core Error

----------------------
2021-05-30T22:46:45-07:00 [INFO][SMF][PduSess] Send NF Discovery Serving UDM Successfully
2021-05-30T22:46:45-07:00 [INFO][UDM][SDM] Handle GetSmData
2021-05-30T22:46:45-07:00 [INFO][UDM][SDM] getSmDataProcedure: SUPI[imsi-2089300007487] PLMNID[20893] DNN[internet] SNssai[{"sst":1,"sd":"010203"}]
2021-05-30T22:46:45-07:00 [INFO][UDR][DataRepo] Handle QuerySmData
2021-05-30T22:46:45-07:00 [INFO][UDR][GIN] | 200 |       127.0.0.1 | GET     | /nudr-dr/v1/subscription-data/imsi-2089300007487/20893/provisioned-data/sm-data?single-nssai=%7B%22sst%22%3A1%2C%22sd%22%3A%22010203%22%7D |

2021/05/30 22:46:45 [Recovery] 2021/05/30 - 22:46:45 panic recovered:
runtime error: makeslice: cap out of range
/usr/local/go/src/runtime/slice.go:31 (0x44b9cf)
	panicmakeslicecap: panic(errorString("makeslice: cap out of range"))
/usr/local/go/src/runtime/slice.go:46 (0x44b9b3)
	makeslice: panicmakeslicecap()
/home/udhay/my5G-core/src/udm/context/context.go:111 (0x9b7a9a)
	(*UDMContext).ManageSmData: AllDnnConfigsbyDnn := make([]models.DnnConfiguration, 1, len(sNssaiList))
/home/udhay/my5G-core/src/udm/producer/subscriber_data_management.go:512 (0xaa6c49)
	getSmDataProcedure: smData, snssaikey, AllDnnConfigsbyDnn, AllDnns := udm_context.UDM_Self().ManageSmData(
/home/udhay/my5G-core/src/udm/producer/subscriber_data_management.go:467 (0xaa637d)
	HandleGetSmDataRequest: response, problemDetails := getSmDataProcedure(supi, plmnID, Dnn, Snssai, supportedFeatures)
/home/udhay/my5G-core/src/udm/subscriberdatamanagement/api_session_management_subscription_data_retrieval.go:32 (0xaba3f2)
	HTTPGetSmData: rsp := producer.HandleGetSmDataRequest(req)
/home/udhay/my5G-core/src/udm/subscriberdatamanagement/routers.go:86 (0xabefd8)
	twoLayerPathHandlerFunc: route.HandlerFunc(c)
/home/udhay/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 (0x922e5a)
	(*Context).Next: c.handlers[c.index](c)
/home/udhay/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/recovery.go:83 (0x9346ff)
	RecoveryWithWriter.func1: c.Next()
/home/udhay/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 (0x922e5a)
	(*Context).Next: c.handlers[c.index](c)
/home/udhay/my5G-core/lib/logger_util/logger_util.go:65 (0x93668d)
	ginToLogrus.func1: c.Next()
/home/udhay/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 (0x922e5a)
	(*Context).Next: c.handlers[c.index](c)
/home/udhay/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:389 (0x92c06f)
	(*Engine).handleHTTPRequest: c.Next()
/home/udhay/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:351 (0x92b8a2)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/home/udhay/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/server.go:2147 (0x97e7aa)
	(*serverConn).runHandler: handler(rw, req)
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x4644b0)
	goexit: BYTE	$0x90	// NOP

2021-05-30T22:46:45-07:00 [INFO][UDM][GIN] | 500 |       127.0.0.1 | GET     | /nudm-sdm/v1/imsi-2089300007487/sm-data?dnn=internet&plmn-id=20893&single-nssai=%7B%22sst%22%3A1%2C%22sd%22%3A%22010203%22%7D |
2021-05-30T22:46:45-07:00 [ERRO][SMF][PduSess] Get SessionManagementSubscriptionData error: undefined response type
2021-05-30T22:46:45-07:00 [INFO][SMF][GSM] In HandlePDUSessionEstablishmentRequest
2021-05-30T22:46:45-07:00 [ERRO][SMF][Context] this SMContext[urn:uuid:3915c321-df5a-4235-be3b-81db58639773] has no subscription pdu session type info

-----------------------------------------------------------------

2021/05/30 22:29:57 http2: server connection error from 127.0.0.1:54716: connection error: PROTOCOL_ERROR
2021-05-30T22:29:57-07:00 [INFO][PCF][SMpolicy] Handle CreateSmPolicy
2021-05-30T22:29:57-07:00 [INFO][UDR][DataRepo] Handle PolicyDataUesUeIdSmDataGet
2021-05-30T22:29:57-07:00 [INFO][UDR][GIN] | 200 |       127.0.0.1 | GET     | /nudr-dr/v1/policy-data/ues/imsi-2089300007487/sm-data?dnn=internet&snssai=%7B%22sst%22%3A1%2C%22sd%22%3A%22010203%22%7D |
2021-05-30T22:29:57-07:00 [INFO][PCF][GIN] | 201 |       127.0.0.1 | POST    | /npcf-smpolicycontrol/v1/sm-policies |
2021-05-30T22:29:57-07:00 [INFO][SMF][PduSess] SUPI[imsi-2089300007487] has no pre-config route
2021-05-30T22:29:57-07:00 [INFO][NRF][Discovery] Handle NFDiscoveryRequest
2021-05-30T22:29:57-07:00 [INFO][NRF][GIN] | 200 |       127.0.0.1 | GET     | /nnrf-disc/v1/nf-instances?requester-nf-type=SMF&target-nf-instance-id=56cbee2a-6eab-4d7e-98ff-5a0a15e5d2d1&target-nf-type=AMF |
2021-05-30T22:29:57-07:00 [INFO][SMF][App] SendNFDiscoveryServingAMF ok
2021-05-30T22:29:57-07:00 [INFO][SMF][PduSess] Send PFCP Rule
2021-05-30T22:29:57-07:00 [INFO][SMF][PduSess] DataPath:  &{true true {  } false 0xc00034f600}
2021-05-30T22:29:57-07:00 [INFO][SMF][GIN] | 201 |       127.0.0.1 | POST    | /nsmf-pdusession/v1/sm-contexts |
2021-05-30T22:29:57-07:00 [INFO][AMF][Gmm] smconetxt ef : urn:uuid:7557764a-a65f-40f9-81cc-5ddb18a5bbd6
2021-05-30T22:29:57-07:00 [INFO][AMF][Gmm] Http create smContext[pduSessionID: 10] Success
2021-05-30T22:29:57-07:00 [INFO][UPF][Util] [PFCP] Handle PFCP session establishment request
2021-05-30T22:29:57-07:00 [INFO][SMF][Pfcp] In HandlePfcpSessionEstablishmentResponse
<nil>
2021-05-30T22:29:57-07:00 [INFO][UPF][Util] [PFCP] Session Establishment Response
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa3efd8]

goroutine 66 [running]:
free5gc/lib/nas/nasConvert.ModelsToSessionAMBR(0x0, 0x0)
	/home/udhay/my5G-core/lib/nas/nasConvert/SessionAMBR.go:19 +0xa8
free5gc/src/smf/context.BuildGSMPDUSessionEstablishmentAccept(0xc00033a000, 0x4, 0x4, 0xc0002c9889, 0x4, 0x4)
	/home/udhay/my5G-core/src/smf/context/gsm_build.go:53 +0x1cb
free5gc/src/smf/pfcp/handler.HandlePfcpSessionEstablishmentResponse(0xc00029dfa0)
	/home/udhay/my5G-core/src/smf/pfcp/handler/handler.go:159 +0x317
free5gc/src/smf/pfcp.Dispatch(0xc00029dfa0)
	/home/udhay/my5G-core/src/smf/pfcp/dispatcher.go:43 +0x49c
created by free5gc/src/smf/pfcp/udp.Run.func1
	/home/udhay/my5G-core/src/smf/pfcp/udp/udp.go:44 +0x1d1
2021-05-30T22:31:57-07:00 [WARN][N3IWF][NWuCP] Connection close by peer

**Comment by dayal007** [comment]
After I reboot, this worked fine

**Comment by dayal007** [comment]
After I reboot, this worked fine
